name: Default - Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - master

env:
  DOTNET_VERSION: '7.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      #- uses: azure/login@v1
      #      with:
      #          creds: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_069034DCD60C4CA7B2DC2E417F3E5FD0 }}
                
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
          include-prerelease: false
        
      - name: Install Nuget
        uses: nuget/setup-nuget@v1
        with:
            nuget-version: ${{ env.NUGET_VERSION}}
        
      - name: Install Required Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
          dotnet restore
          nuget restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: dotnet bundle migration
        run: dotnet ef migrations bundle -p DotNetCoreSqlDb/DotNetCoreSqlDb.csproj -o ${{env.DOTNET_ROOT}}/myapp/bundle
        
      #- name: Deploy the Database Changes
      #  run: ${{env.DOTNET_ROOT}}/myapp/bundle --connection ${{ secrets.CONNECTIONSTRING }}
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'msdocs-core-sql-999'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_069034DCD60C4CA7B2DC2E417F3E5FD0 }}
          package: '.'
